[package]
name = "algorithm_testing"
version = "0.1.0"
edition = "2021"

[dependencies]
brute_force = { version = "0.1.0", path = "../algorithms/brute_force" }
data_types = { version = "0.1.0", path = "../helpers/data_types" }
divide_and_conquer = { version = "0.1.0", path = "../algorithms/divide_and_conquer" }
ron = "0.9.0"
