[workspace]
resolver = "2"
members = [
    "algorithm_testing",
    "algorithms/brute_force",
    "algorithms/divide_and_conquer",
    "helpers/data_generator",
    "helpers/data_types",
    "helpers/measure_execution_time",
]
exclude = []
